### ISSUE TITLE
Disabling default blocks disables all blocks

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/blocks#11]
When disabling default blocks [like mentioned here](https://github.com/getkirby/blocks#disable-default-fieldsets) it disables all blocks for me.

**Comment by afbora** [comment]
You need to set `true` to use defaults. Since the `fieldsets` option is not empty, it is a bit difficult to know whether to use default or custom fields.

````yaml
fields:
  blocks:
    label: Text
    type: blocks
    fieldsets:
      heading: false
      text: false
      image: true
      quote: true
      code: true
      gallery: true
      video: true
      kirbytext: true
````

Maybe an option like `defaults` would be useful:

````yaml
fields:
  blocks:
    label: Text
    type: blocks
    fieldsets:
      defaults: true # new option that load default fieldsets
      heading: false
      text: false
      pages:
        icon: page
        name: Pages
        fields:
          pages:
            type: pages
            layout: cards
````
