### ISSUE TITLE
Easier fieldsetGroups

### ISSUE THREAD

**Issue by Werbschaft** [getkirby/blocks#13]
Would it not make more sense if the fieldsetgroups were defined directly in the fieldsets when possible (example below)? Otherwise you have to create everything twice?

```
fieldsets:
  group_1:
    label: Images 
    accordion: pagebuilder/elements/accordion
    bild: pagebuilder/elements/bild
  group_2:
    label: Others
    bildanmerkungen: pagebuilder/elements/bildanmerkungen
```

**Comment by bastianallgeier** [comment]
I'm quite happy that you brought this up. I solved this last week and the fieldset groups are now combined with fieldsets like this: 

```yaml
fieldsets:
  text:
    label: Text
    type: group
    fieldsets:
      - text
      - heading
      - quote
  media:
    label: Media
    type: group
    fieldsets:
      - image
      - gallery
      - video
```
