### ISSUE TITLE
Layout field doesn't have default fieldsets

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/blocks#15]
While the blocks field automatically has some default fieldsets, the layout field doesn't.

## Blocks
```yml
blocks:
    type: blocks
````

![image](https://user-images.githubusercontent.com/7975568/97428580-77834a80-1916-11eb-8f80-a7a64a4b3437.png)

## Layout
```yml
layout:
    type: layout
    layouts:
      - "1/1"
      - "1/2, 1/2"
```
![image](https://user-images.githubusercontent.com/7975568/97428505-59b5e580-1916-11eb-8601-480397305adc.png)
