### ISSUE TITLE
FieldsetGroups as Accordion

### ISSUE THREAD

**Issue by Werbschaft** [getkirby/blocks#16]
Wouldn't it make more sense that when using fieldsetGroups only one fieldsetGroup can be open instead of all? Means when I open one, all others close immediatly. Currently I have closed all, but when I search for an block I open all others and it looks like before the open:false

Only as an improvement, nothing wild!

**Comment by distantnative** [comment]
Honestly, me personally wouldn't like this change. I'm each time frustrated where such a behavior for accordions is implemented and I want to look at two sections at the same time. It robs the user of quite some agency and to me always feels patronizing.

**Comment by Werbschaft** [comment]
Of course, such an accordion is kind of patronizing, but in this case it could come in handy.

**Comment by distantnative** [comment]
I think we just differ here in taste: for me it would be the worse experience to only be able to see the fieldsets of one group at a glance. And not look at two or more groups at the same time to then decide what I want.

**Comment by Werbschaft** [comment]
Sure, there's a use case for everything! We have the problem that we currently have round about 20 blocks and I'm sure there will come more, so we're searching for a way to get it more clear. Having all blocks at a overview it's definitly too much. But of course, I think here has every user another opinion. The good thing is we can also simply change the grid manually in CSS to get a more compact layout.

<img width="513" alt="Bildschirmfoto 2020-10-29 um 11 49 45" src="https://user-images.githubusercontent.com/2178466/97558945-18d4d400-19dd-11eb-808b-4ac1b42f8cf9.png">

<img width="501" alt="Bildschirmfoto 2020-10-29 um 11 52 51" src="https://user-images.githubusercontent.com/2178466/97559159-5b96ac00-19dd-11eb-856c-8c642433c405.png">

**Comment by distantnative** [comment]
And what about using `open: false` for your use case? Then they start closed but the user still has full control which ones should be open

**Comment by Werbschaft** [comment]
We currently using this feature, only the first group is open for default. But when I want to choose another block and click the group 3 to open, then the group 1 stays open and I lost my focus.

But like said, this is not a very important enhancement, only my opinion 😃

**Comment by aristotheme** [comment]
Hi Werbschaft

How did you do that with blueprints?

**Comment by Werbschaft** [comment]
@aristotheme small example below. Currently a bit complicated in my opinion, cause of that this idea: https://github.com/getkirby/blocks/issues/13

```
fields:
  pagebuilder:
    label: Pagebuilder
    type: layout
    layouts: 
      - "1/1"
      - "1/2, 1/2"
      - "1/4, 1/4, 1/4, 1/4"
    fieldsetGroups:
      group_1:
        label: Group 1
        fieldsets:
          - accordion
          - bild
      group_2:
        label: Group 2
        open: false
        fieldsets:
          - bildanmerkungen
    fieldsets:
      accordion: pagebuilder/elements/accordion
      bild: pagebuilder/elements/bild
      bildanmerkungen: pagebuilder/elements/bildanmerkungen
```
