### ISSUE TITLE
More prominent expand button

### ISSUE THREAD

**Issue by iskrisis** [getkirby/blocks#25]
I know it will be chellange to fit it somewhere BUT from my initial testing with real editors/users i think Expand should be just one click somewhere on fields that have previews.

It's really apparent with Heading that has by default 3 levels and it is important to set which one the heading should be them.

**Comment by bastianallgeier** [comment]
Yeah, that's a real challenge I'm thinking about a lot at the moment. I was also playing with double-click, but it's just not obvious enough.

**Comment by iskrisis** [comment]
I've tried to fit it besides other buttons and i don't think it will fit there. It becomes a pretty tedious with three buttons.

This is pretty heavyhanded but some visual thoughts.
[https://www.dropbox.com/s/7uru41nd2slv35k/kirby-blocks-expand.webm?dl=0](https://www.dropbox.com/s/7uru41nd2slv35k/kirby-blocks-expand.webm?dl=0)

If it doesn't work grouped there maybe it can be in different position. I think there is already this concept of closing the "field blocks" by clicking on header so maybe clicking somewhere on top is place where one would expect it. It seems to work better when boundaries of the block are somehow highlighted but i know you want to keep it super clean and its more busy. There were multiple people saying they like `type: layout` more even for single column builder and i suspect it's because the boundaries are more visible when you hover so maybe it's not such a bad idea to do it somehow.

```css
.k-block-container:hover .k-block {
  border-color: #DBD7D7;
  position: relative;
}

.k-block {
  border-top: 1px solid white;
  border-bottom: 1px solid white;
}

.k-block-container:hover .k-block::before {
  content: "▽";
  position: absolute;
  top: -5px;
  font-size: 15px;
  color: #A8A8A8;
  right: -21px;
}

.k-block-container .k-block:hover::before {
 cursor: s-resize; 
}
```
