### ISSUE TITLE
Groups in layout type

### ISSUE THREAD

**Issue by aristotheme** [getkirby/blocks#29]
I guess It doesn't work like this? It works with **block type**
```
layout:
    type: layout
    layouts:
      - "1/1"
      - "1/2, 1/2"
      - "1/4, 1/4, 1/4, 1/4"
      - "1/3, 2/3"
      - "2/3, 1/3"
      - "1/3, 1/3, 1/3"
    fieldsets:
      text:
        label: Text
        type: group
        fieldsets:
          tx001: fieldsets/tx001

      media:
        label: Media
        type: group
        fieldsets:
          tx002: fieldsets/tx002
```
