### ISSUE TITLE
Call to a member function url() on null

### ISSUE THREAD

**Issue by RustyDev** [getkirby/blocks#32]
I'm using alpha 7 and set up a simple test page with default blocks. I get this error when trying to save it in the panel:

```
code: 500
details: []
exception: "Error"
file: "index.php"
key: null
line: 15
message: "Call to a member function url() on null"
route: "pages/([a-zA-Z0-9\.\-_%= \+\@\(\)]+)"
status: "error"
```

The fields are:
```
title: Content Blocks
preset: page

fields:
  blocks:
    label: Blocks
    type: blocks
```
