### ISSUE TITLE
Nested blocks are not supported yet

### ISSUE THREAD

**Issue by Werbschaft** [getkirby/blocks#35]
If you have nested blocks and want to click another field, the drawer closes again. It is only possible to navigate using the tab key. In addition, scrolling in the drawer is no longer possible, but I just saw that someone has already opened an issue here. Here is a blueprint that can be used, below a video for demonstration

```yaml
pagebuilder:
  label: Blocks
  type: blocks
  fieldsets:
    accordion:
      label: Accordion
      type: blocks
      fields:
        entry:
          label: Element
          type: blocks
          fieldsets:
            name:
              label: Name
              fields:
                element:
                  label: Name
                  type: text
                content:
                  label: Inhalt
                  type: textarea
```

![nested](https://user-images.githubusercontent.com/2178466/98926923-35423780-24d8-11eb-9da1-f638d0f9cfb9.gif)
