### ISSUE TITLE
Can't extend fieldsets in alpha 8

### ISSUE THREAD

**Issue by modufolio** [getkirby/blocks#43]
Extended fieldsets don't seem to work in alpha 8, it worked in alpha 5
```
                fieldsets:

                  accordion:
                    extends: fields/accordion
                    label: Accordion

                  blockquote:
                    extends: fields/blockquote
                    label: Blockquote
```
