### ISSUE TITLE
Default layout & blocks defined in page blueprint

### ISSUE THREAD

**Issue by rasteiner** [getkirby/blocks#51]
Like title says. 

would give editors some consistency, but with the option to change stuff for the exceptions. 

Don't know about the blueprint api, could be something similar to the css grid areas syntax:

```yml
type: layout
layouts:
  full: "1/1"
  halfs: "1/2, 1/2"
  threeone: "3/4, 1/4"
fieldsets:
  - text
  - heading
  - image
  - quote
default:
  - layout: full
    blocks: > 
      heading
      image
  - layout: threeone
    block: > 
      text quote
      .    image
     
```
