### ISSUE TITLE
"The fieldset undefined could not be found" error with Files field in layout settings

### ISSUE THREAD

**Issue by tobimori** [getkirby/blocks#57]
![image](https://user-images.githubusercontent.com/29142128/99417851-ae87c300-28fa-11eb-888a-68763a2467a4.png)

**Comment by bastianallgeier** [comment]
✅

**Comment by tobimori** [comment]
Hi, I'm still experiencing this error.

```
        bgImage:
          label:
            de: Hintergrundbild
            en: Background image
          type: files
          cover: true
          ratio: 16/9
          max: 1
```
