### ISSUE TITLE
Files field in Row Settings doesn't work

### ISSUE THREAD

**Issue by Werbschaft** [getkirby/blocks#62]
For example, if the Files field is used in the Settings row, an error message is displayed.

<img width="518" alt="Bildschirmfoto 2020-11-18 um 23 09 10" src="https://user-images.githubusercontent.com/2178466/99594452-7d3eee00-29f3-11eb-9f68-bd0a825a9743.png">

<img width="690" alt="Bildschirmfoto 2020-11-18 um 23 16 29" src="https://user-images.githubusercontent.com/2178466/99594970-37cef080-29f4-11eb-8073-9b5402b03bf3.png">

**Blueprint to reproduce:**

```yaml
test:
  label: Test
  type: layout
  layouts: 
    - "1/1"
    - "1/2, 1/2"
  settings:
    fields:
      hero:
        type: files
        label: Hero
```
