### ISSUE TITLE
Field type tags are no longer saved correctly

### ISSUE THREAD

**Issue by Werbschaft** [getkirby/blocks#64]
Normally the tags field is output as a comma separated list. But if the Tags field is used in the Builder, in the layouts or in the settings, it is output as an array. Test blueprint below

<img width="540" alt="Bildschirmfoto 2020-11-19 um 09 13 52" src="https://user-images.githubusercontent.com/2178466/99639162-940f3000-2a47-11eb-80c2-4c50eb3e5f11.png">

**Testcase**
```yaml
test:
  label: Text
  type: layout
  layouts: 
    - "1/1"
    - "1/2, 1/2"
  settings:
    fields:
      mynewtags:
        type: tags
          options:
            "mr-auto" : "Left"
            "ml-auto mr-auto" : "Center"
            "ml-auto" : "Right"
  fieldsets:
    tagsfield:
      label: "Tagsfield"
        fields:
          mynewtags:
            type: tags
            options:
              "mr-auto" : "Left"
              "ml-auto mr-auto" : "Center"
              "ml-auto" : "Right"
```
