### ISSUE TITLE
Error on translated name

### ISSUE THREAD

**Issue by mynameisfreedom** [getkirby/blocks#66]
I am getting an error on the translated name, label, and everything else.

```
page:
  icon: page
  name: 
     en: Page
     de: Seite
```
