### ISSUE TITLE
Block called 'list' gets weird preview with non-functioning editing

### ISSUE THREAD

**Issue by tobimori** [getkirby/blocks#69]
![image](https://user-images.githubusercontent.com/29142128/99899643-4266df80-2cab-11eb-8c65-d71153185d5d.png)

**Comment by bastianallgeier** [comment]
How does your blueprint setup look like for this?

**Comment by tobimori** [comment]
```
      list:
        name: Aufzählung
        icon: list-bullet
        fields:        
          structure:
            label: 
              de: Einträge
              en: Entries
            type: structure
            fields:
              text:
                label: 
                  de: Inhalt
                  en: Content
                type: text
              link:
                label: 
                  de: Verlinkung
                  en: Link
                type: url
```

Works fine with an id other than list.
