### ISSUE TITLE
Error if Structure field in settings

### ISSUE THREAD

**Issue by Werbschaft** [getkirby/blocks#70]
If you place a Structure field in the settings the validation will start even though there is nothing to validate. It is currently not possible to place a Structure field in the Settings row.

<img width="370" alt="Bildschirmfoto 2020-11-22 um 19 36 27" src="https://user-images.githubusercontent.com/2178466/99913914-94832180-2cfa-11eb-83c9-f929e1188cdc.png">
<img width="721" alt="Bildschirmfoto 2020-11-22 um 19 37 15" src="https://user-images.githubusercontent.com/2178466/99913917-964ce500-2cfa-11eb-8b46-eca7edbe8a82.png">

**Testcase:**
```yaml
test2:
  label: Text
  type: layout
  layouts: 
    - "1/1"
    - "1/2, 1/2"
  settings:
    fields:
      mystructure:
        label: Structure
        type: structure
        fields:
          field1:
            label: "Field 1"
            type: text
          field2:
            label: "Field 2"
            type: textarea
```
