### ISSUE TITLE
Files field in layout settings does not recognize template settings for filtering on selection

### ISSUE THREAD

**Issue by tobimori** [getkirby/blocks#82]
![image](https://user-images.githubusercontent.com/29142128/100761848-a009d300-33f3-11eb-9ef4-29ee3eecbe9c.png)
![image](https://user-images.githubusercontent.com/29142128/100761881-a8faa480-33f3-11eb-87ba-939b8d5bdd38.png)
Images of the default file template are shown.
New images get the selected file template.

```
        bgImage:
          label:
            de: Hintergrundbild
            en: Background image
          type: files
          cover: true
          ratio: 16/9
          max: 1
          template: background
          parent: site
```

**Comment by afbora** [comment]
@tobimori `files` field doesn't have a `template` option.

You should use `query` option to filter:

````yaml
bgImage:
  label:
    de: Hintergrundbild
    en: Background image
  type: files
  cover: true
  ratio: 16/9
  max: 1
  parent: site
  query: page.images.filterBy('template', 'background')
````

https://getkirby.com/docs/reference/panel/fields/files#querying-files
